moveit/moveit_resources

fanuc_description/LICENSE, fanuc_description/README.md, fanuc_moveit_config/LICENSE, fanuc_moveit_config/README.md
As per subject.
I've opted to simply copy the `LICENSE` file into both directories.
=> Fix for issue #11: add missing license

.travis.yml
This will not work correctly until https://github.com/ros-planning/moveit_ci/pull/53 is merged
=> Moveit2 ci

fanuc_description/CHANGELOG.rst, fanuc_description/package.xml, fanuc_moveit_config/CHANGELOG.rst, fanuc_moveit_config/package.xml, moveit_resources/CHANGELOG.rst, moveit_resources/package.xml, panda_description/CHANGELOG.rst, panda_description/package.xml, panda_moveit_config/CHANGELOG.rst, panda_moveit_config/package.xml, pr2_description/CHANGELOG.rst, pr2_description/package.xml
The only changelog with new content is panda_moveit_config.
=> Changelogs for Noetic 0.7.1

fanuc_description/package.xml, fanuc_moveit_config/package.xml, moveit_resources/package.xml, panda_description/package.xml, pr2_description/package.xml
I haven't been involved in this package for quite a while, but looking at the commit history it seems you're the best one for this role @rhaschke
=> Change package maintainer: Dave to Robert

fanuc_moveit_config/launch/chomp_planning_pipeline.launch.xml, fanuc_moveit_config/launch/move_group.launch, fanuc_moveit_config/launch/ompl_planning_pipeline.launch.xml, fanuc_moveit_config/launch/pilz_industrial_motion_planner_planning_pipeline.launch.xml, fanuc_moveit_config/launch/planning_pipeline.launch.xml, panda_moveit_config/config/ompl_planning.yaml, panda_moveit_config/launch/chomp_planning_pipeline.launch.xml, panda_moveit_config/launch/move_group.launch, panda_moveit_config/launch/ompl_planning_pipeline.launch.xml, panda_moveit_config/launch/pilz_industrial_motion_planner_planning_pipeline.launch.xml, panda_moveit_config/launch/planning_pipeline.launch.xml, prbt_moveit_config/launch/move_group.launch, prbt_moveit_config/launch/ompl_planning_pipeline.launch.xml, prbt_moveit_config/launch/pilz_industrial_motion_planner_planning_pipeline.launch.xml
For testing this, install https://github.com/ros-planning/moveit/pull/2127 and run:
roslaunch moveit_resources_panda_moveit_config demo.launch
=> Run multiple planning pipelines with MoveGroup

README.md, fanuc_moveit_config/config/ros_controllers.yaml
Super sorry, I didn't notice them 
Fixes https://github.com/ros-planning/moveit_resources/pull/54#discussion_r597923426
=> Revert wrong fixes from moveit to MoveIt

fanuc_description/CHANGELOG.rst, fanuc_description/package.xml, fanuc_moveit_config/CHANGELOG.rst, fanuc_moveit_config/package.xml, moveit_resources/CHANGELOG.rst, moveit_resources/package.xml, panda_description/CHANGELOG.rst, panda_description/package.xml, panda_moveit_config/CHANGELOG.rst, panda_moveit_config/package.xml, pr2_description/CHANGELOG.rst, pr2_description/package.xml
git tag 2.0.1 need to be pushed manually once this PR is merged
=> [ROS2]: Update version to 2.0.1

fanuc_description/CHANGELOG.rst, fanuc_description/package.xml, fanuc_moveit_config/CHANGELOG.rst, fanuc_moveit_config/package.xml, moveit_resources/CHANGELOG.rst, moveit_resources/package.xml, panda_description/CHANGELOG.rst, panda_description/package.xml, panda_moveit_config/CHANGELOG.rst, panda_moveit_config/package.xml, pr2_description/CHANGELOG.rst, pr2_description/package.xml, prbt_ikfast_manipulator_plugin/CHANGELOG.rst, prbt_ikfast_manipulator_plugin/package.xml, prbt_moveit_config/CHANGELOG.rst, prbt_moveit_config/package.xml, prbt_pg70_support/CHANGELOG.rst, prbt_pg70_support/package.xml, prbt_support/CHANGELOG.rst, prbt_support/package.xml
Here is the 0.7.3 release we discussed.
=> Prepare 0.7.3 for Melodic

fanuc_description/CHANGELOG.rst, fanuc_description/package.xml, fanuc_moveit_config/CHANGELOG.rst, fanuc_moveit_config/package.xml, moveit_resources/CHANGELOG.rst, moveit_resources/package.xml, panda_description/CHANGELOG.rst, panda_description/package.xml, panda_moveit_config/CHANGELOG.rst, panda_moveit_config/package.xml, pr2_description/CHANGELOG.rst, pr2_description/package.xml, prbt_ikfast_manipulator_plugin/CHANGELOG.rst, prbt_ikfast_manipulator_plugin/package.xml, prbt_moveit_config/CHANGELOG.rst, prbt_moveit_config/package.xml, prbt_pg70_support/CHANGELOG.rst, prbt_pg70_support/package.xml, prbt_support/CHANGELOG.rst, prbt_support/package.xml
@v4hn here is the release prepared for Noetic we talked about.
=> Prepare 0.8.0 for Noetic

.github/workflows/format.yml, .github/workflows/industrial_ci_action.yml, README.md
=> Support Rolling CI

panda_moveit_config/config/panda.urdf.xacro, panda_moveit_config/config/panda_controllers.yaml, panda_moveit_config/config/panda_hand.ros2_control.xacro, panda_moveit_config/config/panda_ros_controllers.yaml
Depends on: https://github.com/ros-controls/ros2_controllers/pull/162 & https://github.com/ros-controls/ros2_control/pull/409
=> Add fake controller for panda_hand

panda_moveit_config/launch/demo.launch.py
This adds the missing hand_controller to the demo.launch file.
=> Add panda_hand_controller to demo.launch.py

fanuc_moveit_config/config/chomp_planning.yaml, fanuc_moveit_config/config/sensors_3d.yaml, fanuc_moveit_config/launch/setup_assistant.launch, panda_moveit_config/config/chomp_planning.yaml, panda_moveit_config/launch/setup_assistant.launch
I wanted to generate new rviz configs for these two configs,
but instead found some other issues first, trying to use the configs
with our current master branch.
I'll try to provide new configs later instead. ;)
=> minor patches

fanuc_moveit_config/launch/test_environment.launch, panda_description/meshes/visual/finger.dae, panda_description/meshes/visual/hand.dae, panda_description/meshes/visual/link0.dae, panda_description/meshes/visual/link1.dae, panda_description/meshes/visual/link2.dae, panda_description/meshes/visual/link3.dae, panda_description/meshes/visual/link4.dae, panda_description/meshes/visual/link5.dae, panda_description/meshes/visual/link6.dae, panda_description/meshes/visual/link7.dae, panda_moveit_config/launch/test_environment.launch
See individual commits for details.
=> Some minor fixes/improvements

panda_moveit_config/config/initial_positions.yaml, panda_moveit_config/config/panda.ros2_control.xacro, panda_moveit_config/config/panda_hand.ros2_control.xacro
=> Update handling of initial joint positions by ros2_control

prbt_ikfast_manipulator_plugin/CMakeLists.txt
Those arguments don't work in MSVC
=> Fix Windows compile

.pre-commit-config.yaml, panda_moveit_config/launch/demo.launch.py, panda_moveit_config/launch/moveit_rviz.launch.py
Add black formatter (same as MoveIt2) for Python (aka Launch) files
=> Black Formatting for Launch Files

fanuc_moveit_config/launch/demo.launch.py, panda_moveit_config/launch/demo.launch.py
Update ros2_control launching, to match the example here:  https://github.com/ros-controls/ros2_control_demos/blob/master/ros2_control_demo_bringup/launch/rrbot.launch.py#L79
=> Launch file ros2_control cleanup

fanuc_moveit_config/config/fanuc.ros2_control.xacro, panda_moveit_config/config/panda.ros2_control.xacro, panda_moveit_config/config/panda_hand.ros2_control.xacro
Signed-off-by: Tyler Weaver <tylerjw@gmail.com>
This was caused by a change in ros2_control: https://github.com/ros-controls/ros2_control/commit/1967cfa179248ce2e72f4f974f20d6e19fe56da4
=> fake_components -> mock_components

panda_moveit_config/config/pilz_industrial_motion_planner_planning.yaml
Add a default planner configuration for the PILZ planner to panda_moveit_config
=> Add pilz_industrial_motion_planner_planning.yaml

prbt_ikfast_manipulator_plugin/package.xml
=> Declare conflict with old Pilz package

panda_moveit_config/config/panda.ros2_control.xacro, panda_moveit_config/config/panda.urdf.xacro, panda_moveit_config/config/panda_hand.ros2_control.xacro, panda_moveit_config/launch/demo.launch.py
Depends on https://github.com/PickNikRobotics/isaac_ros2_control/pull/5
=> Replace Isaac with TopicBased

panda_moveit_config/launch/demo.launch.py
We need the joint limits in the Panda config or TOTG will throw errors as joint limits are now required.
I also made the launch files for the Panda more consistent with what was done in the tutorials: https://github.com/ros-planning/moveit2_tutorials/pull/635
=> Add joint limits to Panda demo launch files + make consistent with tutorials

panda_moveit_config/config/panda.ros2_control.xacro, panda_moveit_config/config/panda_hand.ros2_control.xacro, panda_moveit_config/launch/demo.launch.py
The PR cherry-picks #163 to the ros2 branch
=> Cherry pick TopicBased rename #163

panda_moveit_config/config/bio_ik_kinematics.yaml, panda_moveit_config/config/trac_ik_kinematics.yaml
Needed to demonstrate the new IK Benchmarking repo, and generally good to have!
@robotawi FYI
=> Add bio_ik and TRAC-IK kinematics configs

fanuc_moveit_config/config/fanuc.ros2_control.xacro, fanuc_moveit_config/launch/demo.launch.py, panda_moveit_config/config/panda.ros2_control.xacro, panda_moveit_config/config/panda_hand.ros2_control.xacro, panda_moveit_config/launch/demo.launch.py
=> Backport: Update ros2 control usage (#192)
