fanuc_moveit_config/launch/warehouse.launch

currently this will not launch with the latest version of moveit (kinetic) warehouse_ros_mongo is required as mongo_wrapper_ros.py is no longer in warehouse_ros

changes for warehouse ros mongo

---

package.xml

In https://github.com/ros-planning/moveit/pull/214 I switched our CI to build off of ``ros-base`` instead of ``ros-desktop-full``. This means many ROS packages are not installed by default, which uncovered missing dependencies in the python move_group test causing travis to [fail](https://travis-ci.org/ros-planning/moveit/jobs/159809406):
```
FAILURE: Test Fixture Nodes ['joint_state_publisher', 'robot_state_publisher'] failed to launch
File "/usr/lib/python2.7/unittest/case.py", line 329, in run
testMethod()
File "/opt/ros/kinetic/lib/python2.7/dist-packages/rostest/runner.py", line 121, in fn
self.assert_(not failed, "Test Fixture Nodes %s failed to launch"%failed)
File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
raise self.failureException(msg)
```
Should fix …

Add missing run depends for [robot|joint]_state_publisher

---

fanuc_moveit_config/launch/move_group.launch
panda_moveit_config/launch/chomp_planning_pipeline.launch.xml

We have a new scheme to load all default capabilities since a while.
`MoveGroupExecuteService` was [obsoleted in Kinetic](https://github.com/ros-planning/moveit/pull/94) and [removed in Melodic](https://github.com/ros-planning/moveit/pull/833).
As of https://github.com/ros-planning/moveit/pull/1251, CHOMP uses automatically the hybrid collision detector. No need to manually configure it, which is too fragile by the way.

fanuc_moveit_config: cleanup definition of move_group capabilities

---

.travis.yml
CMakeLists.txt
moveit_resources.repos
package.xml

This PR apply the changes from [PR#24](https://github.com/ros-planning/moveit_resources/pull/24) for the CMakeLists.txt and package.xml (without porting Mara files)

Port CMakeLists.txt & package.xml to ROS2

---

moveit_resources.repos

It looks like the ros2-devel branch was deleted - I'm assuming it was renamed to simply ros2. As noted in https://github.com/ros-planning/moveit2/pull/200 the old reference can break CI.

Update joint_state_publisher dependency

---

fanuc_moveit_config/config/kinematics.yaml
panda_moveit_config/config/kinematics.yaml

Increase timeout accordingly to keep roughly the same behavior.
Afaik kinetic still uses this branch as well, but should not be badly affected.
The default attempt count was 2 there.

remove solver attempts

---

panda_moveit_config/config/panda.srdf
panda_moveit_config/config/panda_arm.xacro

I just noticed that the extended pose is in self collision (did the meshes change?):
The updated pose looks like this:

Fix self-colliding 'extended' pose

---

.travis.yml

According to the removal of the kinetic CI in ros-planning/moveit  [#2294](https://github.com/ros-planning/moveit/pull/2295) the CI can/should? be removed from this repository as well.
It is already causing troubles see #43

Removes kinetic from travis ci testing

---

panda_moveit_config/launch/demo.launch
panda_moveit_config/launch/moveit_rviz.launch

regenerated demo.launch and rviz.launch from setup assistant.
The main motivation for this change is the additional use_rviz argument
through which rviz can be disabled.
The `rviz_tutorial` parameter in moveit_rviz.launch was only ever used
through demo.launch and it's easier to handle the different rviz configurations there.

update panda moveit config

---

fanuc_description/CHANGELOG.rst
fanuc_description/package.xml
fanuc_moveit_config/CHANGELOG.rst
fanuc_moveit_config/package.xml
moveit_resources/CHANGELOG.rst
moveit_resources/package.xml
panda_description/CHANGELOG.rst
panda_description/package.xml
panda_moveit_config/CHANGELOG.rst
panda_moveit_config/package.xml
pr2_description/CHANGELOG.rst
pr2_description/package.xml
prbt_ikfast_manipulator_plugin/CHANGELOG.rst
prbt_ikfast_manipulator_plugin/package.xml
prbt_moveit_config/CHANGELOG.rst
prbt_moveit_config/package.xml
prbt_pg70_support/CHANGELOG.rst
prbt_pg70_support/package.xml
prbt_support/CHANGELOG.rst
prbt_support/package.xml

This should fix the official build farm issues with moveit because it releases the Pilz robots.
lmk if this will cause any issues.  My understanding is that in order to do a melodic/noetic release we need to first release this.

Prepare Release for Noetic/Melodic 0.7.2

---

fanuc_moveit_config/launch/demo.launch
panda_moveit_config/launch/demo.launch
prbt_moveit_config/launch/demo.launch

Required to invoke demo.launch use_rviz:=false with execution speedup for tests.
See https://github.com/ros-planning/moveit/pull/2602
for the corresponding patch in the setup assistant.

Let users specify fake execution type for demo.launch

---

panda_moveit_config/config/panda_ros_controllers.yaml

These are required per https://github.com/ros-controls/ros2_controllers/commit/612f610c24d026a41abd2dd026902c672cf778c9 and for fixing CI (https://github.com/ros-planning/moveit2/runs/2633357612#step:7:6223)

Add missing ros2_control parameters

---

panda_moveit_config/config/panda_arm.xacro
panda_moveit_config/launch/demo.launch

The virtual joint type set to `floating` seems to break things when doing benchmarks with the _moveit_ros_benchmarks_ package. 
The first issue I had was with STOMP with cartesian goal constraints which you can read [here](https://github.com/ros-industrial/stomp_ros/issues/34). Changing the joint type to fixed resolves the problem but it may not be the culprit.
The second issue is only occurring when I populate a scene with meshes (tried different meshes and reduced to only one). The left image is a joint constraint goal and the blue line is the path retrieved from STOMP. The left end of the path is the start state and the right end of the segment is the goal state. The left image is with the fixed virtual joint and is the correct planning scene. The right image was taken with the virtual …

Restore virtual joint type to fixed in SRDF

---

panda_moveit_config/config/ompl_planning.yaml

This planner is not available upstream in OMPL for now
- it's work in progress to the best of my knowledge.
It can easily confuse users to have the option available here
when it will not plan anything but complain on the command line
that the solver does not exist...
@mamoll

remove ompl TrajOpt planner config

---

fanuc_moveit_config/config/ros_controllers.yaml
panda_moveit_config/config/panda_ros_controllers.yaml
panda_moveit_config/launch/demo.launch.py

With https://github.com/ros-controls/ros2_controllers/pull/230 ros2_control now removed joint_state_controller in favor of joint_state_broadcaster. This PR migrates `moveit_resources` to joint_state_broadcaster

Migrate to joint state broadcaster

---

panda_moveit_config/launch/demo.launch

https://github.com/ros-planning/moveit/pull/2769 changed the MSA to always generate the static broadcaster for virtual joints.
This repairs the panda moveit config to include this virtual joint again.
Required to fix MTC pick-place demo.
Fixes #89

add missing broadcaster for virtual joint back

---

prbt_moveit_config/launch/demo.launch
prbt_moveit_config/launch/move_group.launch

- Introduce `use_rviz` argument to avoid starting rviz
- Forward `gripper` argument through `demo.launch` to `move_group.launch`
Fixes 9c75ca59edb97b2d83d03acf9d38e977ff3a9b74

Fix PRBT's test_environment.launch

---

panda_moveit_config/config/initial_positions.yaml
panda_moveit_config/config/panda.ros2_control.xacro
panda_moveit_config/config/panda_hand.ros2_control.xacro

This is a temporary fix to get CI passing. See the conversation here:
https://github.com/ros-planning/moveit2/pull/980#issuecomment-1019389113

Do not define Panda initial velocities

---

panda_moveit_config/launch/demo.launch.py

Refactor the panda launch file to use moveit_configs_utils
Should resolve the launch portion of #115 for the panda

Refactor panda demo.launch to use moveit_configs_utils

---

panda_moveit_config/launch/demo.launch.py

Fix the following error when launching `demo.launch.py`
`Caught exception in launch (see debug for traceback): stdoutstderr is not a valid standard output config i.e. "screen", "log" or "both"`

Fix controller_manager node's output type

---

panda_moveit_config/launch/demo.launch.py

Explicitly use CHOMP, OMPL, and Pilz as planners rather than iterating through all `*_planning.yaml` files, some of which do not work as of now.
Partially resolves #134

Explicitly use CHOMP and OMPL planners

---

panda_moveit_config/config/moveit_controllers.yaml

`moveit_controllers.yaml` is inconsistent with `gripper_moveit_controllers.yaml`, which ihas the controller_names and declarations within the `moveit_simple_controller_manager` namespace.

Proper scoping for controllers in Panda Config

---

fanuc_moveit_config/config/sensors_3d.yaml

This is causing problems for https://github.com/ros-planning/moveit2/pull/1387 and has been bugging me for awhile.

Remove fanuc's invalid sensor config

---

fanuc_moveit_config/config/pilz_cartesian_limits.yaml
panda_moveit_config/config/pilz_cartesian_limits.yaml

I think it makes sense to specify this is only for Pilz. [Users were getting confused](https://answers.ros.org/question/403542/set-cartesian-limits-with-moveit/).
Merge with https://github.com/ros-planning/moveit2/pull/1422

Rename cartesian_limits.yaml -> pilz_cartesian_limits.yaml

---

dual_panda_moveit_config/package.xml

Disabling run dependencies to avoid circular dependencies error, same as the panda_moveit_config package.

Fix dependencies for panda dual arm environment

---

.github/workflows/industrial_ci_action.yml

Foxy and Galactic are not really supported in combination with the MoveIt 2 distro branches. We now have dedicated branches `foxy` and `galactic` that match the released versions and that should be used by anyone who wants to build older distros from source.

Remove build jobs for Foxy, Galactic

---

panda_moveit_config/launch/demo.launch.py

In #135, Pilz was removed from the launch file due to some issues with it. These have since been resolved (https://github.com/ros-planning/moveit2/pull/1281), so this PR adds Pilz back to the panda launch file.

Add Pilz to panda launch

---

panda_moveit_config/config/panda.ros2_control.xacro

When running the following command, a warning was displayed suggesting to use `xacro.load_yaml` instead of `load_yaml`.
`ros2 launch moveit_task_constructor_demo demo.launch.py`
The first method is now used instead of the second one.

Removed warning about using deprecated load_yaml method.

---

.github/workflows/format.yml
.github/workflows/industrial_ci_action.yml
.github/workflows/prerelease.yml
.pre-commit-config.yaml

Our ros2 branch target humble/rolling and ubuntu 22.04 is the only tier 1 platform. this PR avoid using ubuntu-latest and pin the version + update clang-format to 12

Pin ubuntu version and update clang-format

---

fanuc_moveit_config/config/moveit_controllers.yaml
panda_moveit_config/config/moveit_controllers.yaml

Inspired by a user question in this issue:  https://github.com/ros-planning/moveit2/issues/1848
Let's add this to the yaml for better documentation.

Add execution_duration_monitoring param to the example config

---

panda_moveit_config/config/panda.ros2_control.xacro
panda_moveit_config/config/panda.urdf.xacro
panda_moveit_config/config/panda_hand.ros2_control.xacro
panda_moveit_config/launch/demo.launch.py

This depends on https://github.com/ros-planning/moveit2/pull/1805.
This's needed for a tutorial I'm writing on how to use moveit with isaac through https://github.com/PickNikRobotics/isaac_ros2_control/
I bet we could add gazebo and ignition without any problem, but I didn't test it!
```xml
<xacro:if value="${ros2_control_hardware_type == 'gazebo'}">
<plugin>gazebo_ros2_control/GazeboSystem</plugin>
</xacro:if>
<xacro:if value="${ros2_control_hardware_type  == 'ignition'}">
<plugin>ign_ros2_control/IgnitionSystem</plugin>
</xacro:if>
```

[ROS2]: Add a new parameter to panda's xacro to select ros2_control hardware interface type

---

benchmarking/launch/run_benchmark.launch.py
fanuc_moveit_config/config/ompl_planning.yaml
panda_moveit_config/config/ompl_planning.yaml

This PR does two things:
- Update some wrong filenames of the benchmarking launch file
- Add the config necessary use AnytimePathShortening

Enable anytime and fix benchmarks

---

dual_arm_panda_moveit_config/config/ompl_planning.yaml
fanuc_moveit_config/config/ompl_planning.yaml
panda_moveit_config/config/ompl_planning.yaml

The [YAML specification](https://yaml.org/spec/1.2-old/spec.html#id2767100) does not support comments inside scalars, such as the one used to specify `request_adapters`. These lines will not be interpreted correctly. This PR moves the comments outside of the scalar such that they are properly interpreted as comments.
I wrote [this script](https://gist.github.com/stephanie-eng/6fd434a631a9a2d8d5c39ff33642b8df) to check the repo for all potential issues of this nature and fixed the three that it found.

Remove comments from scalars

---

panda_description/urdf/panda.urdf

This adds proper inertials to the Panda URDF (from https://github.com/frankaemika/franka_ros/blob/develop/franka_description/robots/common/inertial.yaml), and uses file URI's that Gazebo can understand.
This is an isolated step to enable Gazebo support. Launch file changes will follow, but they are a bit more tricky since they require handling of Humble/Rolling differences.

Fix Panda description for Gazebo Sim

---

panda_description/README.md
panda_description/urdf/panda.urdf.xacro
panda_moveit_config/config/panda.urdf.xacro

This should fix the failing MoveIt CI, since RobotModelTestUtils doesn't evaluate xacro functions.
Testing with this PR https://github.com/ros-planning/moveit2/pull/2217
... Ok, confirmed to fix CI

Create Panda URDF Xacro, restore URDF for RobotModelTestUtils

---

dual_arm_panda_moveit_config/config/panda.ros2_control.xacro
fanuc_moveit_config/config/fanuc.ros2_control.xacro

Fix warnings about the deprecation of `load_yaml` in macros `panda_arm_ros2_control` and `fanuc_ros2_control` in the same way they have been fixed in https://github.com/ros-planning/moveit_resources/pull/156 for macro `panda_ros2_control`.

fix warnings about deprecated load_yaml

---

dual_arm_panda_moveit_config/config/ompl_planning.yaml
fanuc_moveit_config/config/chomp_planning.yaml
fanuc_moveit_config/config/ompl_planning.yaml
panda_moveit_config/config/chomp_planning.yaml
panda_moveit_config/config/ompl_planning.yaml
panda_moveit_config/config/pilz_industrial_motion_planner_planning.yaml
panda_moveit_config/config/stomp_planning.yaml

Blocked by https://github.com/ros-planning/moveit2/pull/2457
Makes the planner plugin parameter a vector.

Update planner plugin configs

---

dual_arm_panda_moveit_config/config/panda.ros2_control.xacro
dual_arm_panda_moveit_config/config/panda_hand.ros2_control.xacro
dual_arm_panda_moveit_config/launch/demo.launch.py
fanuc_moveit_config/config/fanuc.ros2_control.xacro
fanuc_moveit_config/launch/demo.launch.py
panda_moveit_config/config/panda.ros2_control.xacro
panda_moveit_config/config/panda_hand.ros2_control.xacro
panda_moveit_config/launch/demo.launch.py

Addresses these deprecation warnings
```
[Deprecated] Passing the robot description parameter directly to the control_manager node is deprecated. Use '~/robot_description' topic from 'robot_state_publisher' instead.
```
and
```
Parsing of optional initial interface values failed or uses a deprecated format. Add initial values for every state interface in the ros2_control.xacro. For example:
[ros2_control_node-5] <state_interface name="velocity">
[ros2_control_node-5]   <param name="initial_value">0.0</param>
[ros2_control_node-5] </state_interface>
```

Update ros2 control usage

---

dual_arm_panda_moveit_config/config/ros2_controllers.yaml
fanuc_moveit_config/config/ros2_controllers.yaml
panda_moveit_config/config/ros2_controllers.yaml

While fixing https://github.com/ros-planning/moveit2/issues/2733, I noticed that this was now needed for our servo configs if we are using the acceleration limited plugin.
This has been needed since November 2023 for this use case: https://github.com/ros-controls/ros2_controllers/pull/834, noting the parameter only exists on Rolling, and not on Humble.
cc @ibrahiminfinite

Allow nonzero velocity at trajectory end for ros2_controllers

---

dual_arm_panda_moveit_config/config/panda_hand.ros2_control.xacro
panda_moveit_config/config/panda_hand.ros2_control.xacro

I was trying to use this package on Rolling / Ubuntu 24.04 and ran into this problem.
Found it was related to https://github.com/ros-controls/ros2_control/pull/1553, in which the `<mimic>` tags have been deprecated as this information is now looked up directly from URDF.
So these tags, and command interfaces, for mimic joints, should be removed.

Remove mimic tags from ros2_control URDF in Panda descriptions

---

panda_moveit_config/config/hard_joint_limits.yaml
panda_moveit_config/config/joint_limits.yaml

These jerk limits have been tested on a robot that's approximately UR5-sized.
I think it will be good to have jerk limits in this example so the jerk-limited smoothing features can be used, if desired.

Add reasonable joint jerk limits for the Panda
